name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  title:  
    description: 'title of issue'
    required: true
    default: 'default'
runs:
  using: 'node12'
  main: 'dist/index.js'
